spring.profiles.active=dev

spring.datasource.url=jdbc:mysql-bolao10.up.railway.app:3306/railway
spring.datasource.username=root
spring.datasource.password=FOfEeFfnAVgexhLDHYPHDBeQNlpVTuIK
spring.jpa.hibernate.ddl-auto=none