###### General ######
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jackson.serialization.fail-on-empty-beans=false

#banco de dados - ok
spring.datasource.url=jdbc:mysql://mysqlserver.cmyqguhhw6ym.sa-east-1.rds.amazonaws.com:3306/bolao10?autoReconnect=true&useSSL=false
spring.datasource.username=admin
spring.datasource.password=Aq12wsde3
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow

#custom - ok
custom.jwtkey=M76WuY5e14piICQG6gcwtk6P3SQiLUlZShuD6qhxkNWtPm1M