###### General ######
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jackson.serialization.fail-on-empty-beans=false

#banco de dados
#spring.datasource.url=jdbc:mysql://localhost:3306/bolao10-2026?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.username=root
#spring.datasource.password=123456

#spring.datasource.url=jdbc:mysql://localhost:3306/bolao102026
#spring.datasource.username=bola2026
#spring.datasource.password=senhaApp123

spring.datasource.url=jdbc:mysql://191.252.104.218:3306/alves_bolao10
spring.datasource.username=alves_bolao10
spring.datasource.password=#D!oKpjksKEFx4_Bft

#spring.datasource.url=jdbc:mysql://bolao10-mysql.up.railway.app:3306/railway
#spring.datasource.username=root
#spring.datasource.password=FOfEeFfnAVgexhLDHYPHDBeQNlpVTuIK

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:mysql://mysqlserver.cmyqguhhw6ym.sa-east-1.rds.amazonaws.com:3306/bolao10?autoReconnect=true&useSSL=false
#spring.datasource.username=admin
#spring.datasource.password=Aq12wsde3
#spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.event.merge.entity_copy_observer=allow

#custom
custom.jwtkey=37f6e3b6d0458a456699c2a7c84c8656
