spring.profiles.active=dev

spring.datasource.url=jdbc:mysql://191.252.104.218:3306/ccsalves_planeja_deidt
spring.datasource.username=ccsalves_pdeidt
spring.datasource.password=589sKfrLxLarfgD
spring.jpa.hibernate.ddl-auto=none